blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/rpothin/PowerPlatform-ChristmasApps-FindTheBugsChallenge/discussions/categories/q-a
    about: If you have a question regarding the challenge, follow this link.